services:
  db:
    image: postgres:15.10
    environment:
      POSTGRES_USER: msf
      POSTGRES_PASSWORD: msf
      POSTGRES_DB: msf
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data: